//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Sandbox")]
[assembly: System.Reflection.AssemblyProduct("Sandbox")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2013. All rights reserved.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.e6f7093")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0")]


