//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRoutes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartRoutes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACSI Description.
        /// </summary>
        public static string ACSIDescription {
            get {
                return ResourceManager.GetString("ACSIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACSI.
        /// </summary>
        public static string ACSIName {
            get {
                return ResourceManager.GetString("ACSIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.acsiglobal.org/.
        /// </summary>
        public static string ACSIURL {
            get {
                return ResourceManager.GetString("ACSIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant.
        /// </summary>
        public static string AgeGroupInfantName {
            get {
                return ResourceManager.GetString("AgeGroupInfantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older Toddler.
        /// </summary>
        public static string AgeGroupOlderToddlerName {
            get {
                return ResourceManager.GetString("AgeGroupOlderToddlerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preschool.
        /// </summary>
        public static string AgeGroupPreschoolerName {
            get {
                return ResourceManager.GetString("AgeGroupPreschoolerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Age.
        /// </summary>
        public static string AgeGroupSchoolAgeName {
            get {
                return ResourceManager.GetString("AgeGroupSchoolAgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Younger Toddler.
        /// </summary>
        public static string AgeGroupYoungToddlerName {
            get {
                return ResourceManager.GetString("AgeGroupYoungToddlerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCFP Description.
        /// </summary>
        public static string CCFPDescription {
            get {
                return ResourceManager.GetString("CCFPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCFP.
        /// </summary>
        public static string CCFPName {
            get {
                return ResourceManager.GetString("CCFPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4c.org/provider/participate/food/overview.html.
        /// </summary>
        public static string CCFPURL {
            get {
                return ResourceManager.GetString("CCFPURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COA Description.
        /// </summary>
        public static string COADescription {
            get {
                return ResourceManager.GetString("COADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COA.
        /// </summary>
        public static string COAName {
            get {
                return ResourceManager.GetString("COAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.childrenofamerica.com/.
        /// </summary>
        public static string COAURL {
            get {
                return ResourceManager.GetString("COAURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Camp Description.
        /// </summary>
        public static string DayCampDescription {
            get {
                return ResourceManager.GetString("DayCampDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Camp.
        /// </summary>
        public static string DayCampName {
            get {
                return ResourceManager.GetString("DayCampName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline features of the website here.  This will outline the search process that we will take the user through and ask that they provide feedback on his or her experience with our service..
        /// </summary>
        public static string descriptionText {
            get {
                return ResourceManager.GetString("descriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string descriptionTitleText {
            get {
                return ResourceManager.GetString("descriptionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed Center Description.
        /// </summary>
        public static string LicensedCenterDescription {
            get {
                return ResourceManager.GetString("LicensedCenterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed Center.
        /// </summary>
        public static string LicensedCenterName {
            get {
                return ResourceManager.GetString("LicensedCenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NACCP Description.
        /// </summary>
        public static string NACCPDescription {
            get {
                return ResourceManager.GetString("NACCPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NACCP.
        /// </summary>
        public static string NACCPName {
            get {
                return ResourceManager.GetString("NACCPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.earlylearningleaders.org/.
        /// </summary>
        public static string NACCPURL {
            get {
                return ResourceManager.GetString("NACCPURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAEYC Description.
        /// </summary>
        public static string NAEYCDescription {
            get {
                return ResourceManager.GetString("NAEYCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAEYC.
        /// </summary>
        public static string NAEYCName {
            get {
                return ResourceManager.GetString("NAEYCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.naeyc.org/.
        /// </summary>
        public static string NAEYCURL {
            get {
                return ResourceManager.GetString("NAEYCURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAFCC Description.
        /// </summary>
        public static string NAFCCDescription {
            get {
                return ResourceManager.GetString("NAFCCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAFCC.
        /// </summary>
        public static string NAFCCName {
            get {
                return ResourceManager.GetString("NAFCCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nafcc.org/.
        /// </summary>
        public static string NAFCCURL {
            get {
                return ResourceManager.GetString("NAFCCURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NECPA Description.
        /// </summary>
        public static string NECPADescription {
            get {
                return ResourceManager.GetString("NECPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NECPA.
        /// </summary>
        public static string NECPAName {
            get {
                return ResourceManager.GetString("NECPAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.necpa.net/.
        /// </summary>
        public static string NECPAURL {
            get {
                return ResourceManager.GetString("NECPAURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string portalTextFeedback {
            get {
                return ResourceManager.GetString("portalTextFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string portalTextPlan {
            get {
                return ResourceManager.GetString("portalTextPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type A Home Description.
        /// </summary>
        public static string TypeAHomeDescription {
            get {
                return ResourceManager.GetString("TypeAHomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type A.
        /// </summary>
        public static string TypeAHomeName {
            get {
                return ResourceManager.GetString("TypeAHomeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type B Home Description.
        /// </summary>
        public static string TypeBHomeDescription {
            get {
                return ResourceManager.GetString("TypeBHomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type B.
        /// </summary>
        public static string TypeBHomeName {
            get {
                return ResourceManager.GetString("TypeBHomeName", resourceCulture);
            }
        }
    }
}
