//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRoutes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartRoutes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACSI Description.
        /// </summary>
        internal static string ACSIDescription {
            get {
                return ResourceManager.GetString("ACSIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACSI.
        /// </summary>
        internal static string ACSIName {
            get {
                return ResourceManager.GetString("ACSIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.acsiglobal.org/.
        /// </summary>
        internal static string ACSIURL {
            get {
                return ResourceManager.GetString("ACSIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCFP Description.
        /// </summary>
        internal static string CCFPDescription {
            get {
                return ResourceManager.GetString("CCFPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCFP.
        /// </summary>
        internal static string CCFPName {
            get {
                return ResourceManager.GetString("CCFPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4c.org/provider/participate/food/overview.html.
        /// </summary>
        internal static string CCFPURL {
            get {
                return ResourceManager.GetString("CCFPURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COA Description.
        /// </summary>
        internal static string COADescription {
            get {
                return ResourceManager.GetString("COADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COA.
        /// </summary>
        internal static string COAName {
            get {
                return ResourceManager.GetString("COAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.childrenofamerica.com/.
        /// </summary>
        internal static string COAURL {
            get {
                return ResourceManager.GetString("COAURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline features of the website here.  This will outline the search process that we will take the user through and ask that they provide feedback on his or her experience with our service..
        /// </summary>
        internal static string descriptionText {
            get {
                return ResourceManager.GetString("descriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string descriptionTitleText {
            get {
                return ResourceManager.GetString("descriptionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NACCP Description.
        /// </summary>
        internal static string NACCPDescription {
            get {
                return ResourceManager.GetString("NACCPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NACCP.
        /// </summary>
        internal static string NACCPName {
            get {
                return ResourceManager.GetString("NACCPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.earlylearningleaders.org/.
        /// </summary>
        internal static string NACCPURL {
            get {
                return ResourceManager.GetString("NACCPURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAEYC Description.
        /// </summary>
        internal static string NAEYCDescription {
            get {
                return ResourceManager.GetString("NAEYCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAEYC.
        /// </summary>
        internal static string NAEYCName {
            get {
                return ResourceManager.GetString("NAEYCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.naeyc.org/.
        /// </summary>
        internal static string NAEYCURL {
            get {
                return ResourceManager.GetString("NAEYCURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAFCC Description.
        /// </summary>
        internal static string NAFCCDescription {
            get {
                return ResourceManager.GetString("NAFCCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAFCC.
        /// </summary>
        internal static string NAFCCName {
            get {
                return ResourceManager.GetString("NAFCCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nafcc.org/.
        /// </summary>
        internal static string NAFCCURL {
            get {
                return ResourceManager.GetString("NAFCCURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NECPA Description.
        /// </summary>
        internal static string NECPADescription {
            get {
                return ResourceManager.GetString("NECPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NECPA.
        /// </summary>
        internal static string NECPAName {
            get {
                return ResourceManager.GetString("NECPAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.necpa.net/.
        /// </summary>
        internal static string NECPAURL {
            get {
                return ResourceManager.GetString("NECPAURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string portalTextFeedback {
            get {
                return ResourceManager.GetString("portalTextFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string portalTextPlan {
            get {
                return ResourceManager.GetString("portalTextPlan", resourceCulture);
            }
        }
    }
}
