//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRoutes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartRoutes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Association of Christian Schools International (ACSI) is the largest Protestant educational organization in the world. Since 1978, ACSI has advanced excellence in Christian schools by enhancing the professional and personal development of Christian educators and providing support functions for Christian schools..
        /// </summary>
        public static string ACSIDescription {
            get {
                return ResourceManager.GetString("ACSIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACSI.
        /// </summary>
        public static string ACSIName {
            get {
                return ResourceManager.GetString("ACSIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.acsiglobal.org/.
        /// </summary>
        public static string ACSIURL {
            get {
                return ResourceManager.GetString("ACSIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant.
        /// </summary>
        public static string AgeGroupInfantName {
            get {
                return ResourceManager.GetString("AgeGroupInfantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older Toddler.
        /// </summary>
        public static string AgeGroupOlderToddlerName {
            get {
                return ResourceManager.GetString("AgeGroupOlderToddlerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preschool.
        /// </summary>
        public static string AgeGroupPreschoolerName {
            get {
                return ResourceManager.GetString("AgeGroupPreschoolerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Age.
        /// </summary>
        public static string AgeGroupSchoolAgeName {
            get {
                return ResourceManager.GetString("AgeGroupSchoolAgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Younger Toddler.
        /// </summary>
        public static string AgeGroupYoungToddlerName {
            get {
                return ResourceManager.GetString("AgeGroupYoungToddlerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4Cs sponsors the federally funded Child Care Food Program (CCFP) to ensure that children receive nutritious, well-balanced meals while in day care. The CCFP reimburses licensed child care providers and license exempt TrustLined providers for serving meals and snacks that meet the USDA requirements to the children in their care..
        /// </summary>
        public static string CCFPDescription {
            get {
                return ResourceManager.GetString("CCFPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCFP.
        /// </summary>
        public static string CCFPName {
            get {
                return ResourceManager.GetString("CCFPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4c.org/provider/participate/food/overview.html.
        /// </summary>
        public static string CCFPURL {
            get {
                return ResourceManager.GetString("CCFPURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children of America&apos;s commitment is to provide a safe, developmentally appropriate environment for infants through elementary school. Our emphasis is to provide a stimulating and educational experience that promotes every child&apos;s social, emotional, physical and cognitive development. We deliver educational programs that foster self-esteem, encourage curiosity and inspire children&apos;s desire to be lifelong learners..
        /// </summary>
        public static string COADescription {
            get {
                return ResourceManager.GetString("COADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COA.
        /// </summary>
        public static string COAName {
            get {
                return ResourceManager.GetString("COAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.childrenofamerica.com/.
        /// </summary>
        public static string COAURL {
            get {
                return ResourceManager.GetString("COAURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program which cares for only school age children and operates for less than seven hours each day during the time school is not in session, and the program operates at least 50% outdoors. Child day camps must register with ODJFS each year. To receive reimbursement for publicly funded child care, the child day camp must be accredited by the American Camping Association (ACA) and submit the certificate annually with the day camp registration..
        /// </summary>
        public static string DayCampDescription {
            get {
                return ResourceManager.GetString("DayCampDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Camp.
        /// </summary>
        public static string DayCampName {
            get {
                return ResourceManager.GetString("DayCampName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents who depend on the public transportation often have difficulty finding child care services that are bus accessible. SmartRoutes is a web application that allows parents to search for child care services, ranking the results by how accessible they are via bus to their home and work. SmartRoutes takes a user’s start location, end location, and time of day to provide complete travel itineraries. To that end, the project will package the technology that drives SmartRoutes into a Software Developers Kit.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string descriptionText {
            get {
                return ResourceManager.GetString("descriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string descriptionTitleText {
            get {
                return ResourceManager.GetString("descriptionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no results to display..
        /// </summary>
        public static string ErrorNoResults {
            get {
                return ResourceManager.GetString("ErrorNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 or more children at one time, 7 to 12 children if not in a home..
        /// </summary>
        public static string LicensedCenterDescription {
            get {
                return ResourceManager.GetString("LicensedCenterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed Center.
        /// </summary>
        public static string LicensedCenterName {
            get {
                return ResourceManager.GetString("LicensedCenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Association for Early Learning Leaders is committed to excel­lence in the field of Early Care and Education by promoting lead­ership development and enhancing program quality..
        /// </summary>
        public static string NACCPDescription {
            get {
                return ResourceManager.GetString("NACCPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NACCP.
        /// </summary>
        public static string NACCPName {
            get {
                return ResourceManager.GetString("NACCPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.earlylearningleaders.org/.
        /// </summary>
        public static string NACCPURL {
            get {
                return ResourceManager.GetString("NACCPURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAEYC&apos;s mission is to serve and act on behalf of the needs, rights and well-being of all young children with primary focus on the provision of educational and developmental services and resources..
        /// </summary>
        public static string NAEYCDescription {
            get {
                return ResourceManager.GetString("NAEYCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAEYC.
        /// </summary>
        public static string NAEYCName {
            get {
                return ResourceManager.GetString("NAEYCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.naeyc.org/.
        /// </summary>
        public static string NAEYCURL {
            get {
                return ResourceManager.GetString("NAEYCURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation currently unavailable..
        /// </summary>
        public static string NAFCCDescription {
            get {
                return ResourceManager.GetString("NAFCCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAFCC.
        /// </summary>
        public static string NAFCCName {
            get {
                return ResourceManager.GetString("NAFCCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nafcc.org/.
        /// </summary>
        public static string NAFCCURL {
            get {
                return ResourceManager.GetString("NAFCCURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The National Early Childhood Program Accreditation was established in 1991 to encourage quality and recognize excellence in early childhood programs throughout the United States and other countries.  We pledge to remain focused on the interests of children by promoting benchmarks for high quality standards throughout the early care and education profession..
        /// </summary>
        public static string NECPADescription {
            get {
                return ResourceManager.GetString("NECPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NECPA.
        /// </summary>
        public static string NECPAName {
            get {
                return ResourceManager.GetString("NECPAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.necpa.net/.
        /// </summary>
        public static string NECPAURL {
            get {
                return ResourceManager.GetString("NECPAURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #/feedback.
        /// </summary>
        public static string PageRouteFeedback {
            get {
                return ResourceManager.GetString("PageRouteFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string PageRouteHome {
            get {
                return ResourceManager.GetString("PageRouteHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #/results.
        /// </summary>
        public static string PageRouteResults {
            get {
                return ResourceManager.GetString("PageRouteResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #/search.
        /// </summary>
        public static string PageRouteSearch {
            get {
                return ResourceManager.GetString("PageRouteSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string portalTextBackToResults {
            get {
                return ResourceManager.GetString("portalTextBackToResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string portalTextFeedback {
            get {
                return ResourceManager.GetString("portalTextFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string portalTextHome {
            get {
                return ResourceManager.GetString("portalTextHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string portalTextPlan {
            get {
                return ResourceManager.GetString("portalTextPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 to 12 children (or 4 to 12 children if 4 children are under 2 years of age) cared for in the provider’s home. The provider&apos;s own children under 6 years of age must be included in the total count..
        /// </summary>
        public static string TypeAHomeDescription {
            get {
                return ResourceManager.GetString("TypeAHomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type A.
        /// </summary>
        public static string TypeAHomeName {
            get {
                return ResourceManager.GetString("TypeAHomeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 to 6 children cared for in the provider&apos;s personal home. No more than three children may be under the age of two. The provider&apos;s own children under six years of age must be included in the total count. Type B Homes are only licensed by ODJFS if they serve, or intend to serve, children through the publicly funded child care program. Please note: anyone can operate a Type B Home without a license..
        /// </summary>
        public static string TypeBHomeDescription {
            get {
                return ResourceManager.GetString("TypeBHomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type B.
        /// </summary>
        public static string TypeBHomeName {
            get {
                return ResourceManager.GetString("TypeBHomeName", resourceCulture);
            }
        }
    }
}
